// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BridgePort():Promise<number>;

export function BridgeTokenShort():Promise<string>;

export function CreateBottle(arg1:string):Promise<main.BottleSummary>;

export function DeleteBottle(arg1:string):Promise<void>;

export function ListBottles():Promise<Array<main.BottleSummary>>;
