// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BridgePort() {
  return window['go']['main']['App']['BridgePort']();
}

export function BridgeTokenShort() {
  return window['go']['main']['App']['BridgeTokenShort']();
}

export function CreateBottle(arg1) {
  return window['go']['main']['App']['CreateBottle'](arg1);
}

export function DeleteBottle(arg1) {
  return window['go']['main']['App']['DeleteBottle'](arg1);
}

export function ListBottles() {
  return window['go']['main']['App']['ListBottles']();
}
